## Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#version: 2.1
## Use a package of configuration called an orb.
#orbs:
#  # Declare a dependency on the welcome-orb
#  welcome: circleci/welcome-orb@0.4.1
## Orchestrate or schedule a set of jobs
#workflows:
#  # Name the workflow "welcome"
#  welcome:
#    # Run the welcome/run job in its own container
#    jobs:
#      - welcome/run

#
#version: 2
#jobs:
#  build:
#    docker:
#      - image: circleci/node:7.10
#    steps:
#      - run: echo build
#
#  test:
#    docker:
#      - image: circleci/node:7.10
#    steps:
#      - run: echo test job
#
#  deploy:
#    docker:
#      - image: circleci/node:7.10
#    steps:
#      - run: echo deploy job
#
#
#workflows:
#  version: 2
#  # Name the workflow "welcome"
#  build-and-test:
#    # Run the welcome/run job in its own container
#    jobs:
#      - build
#      - test
#  build-and-deploy:
#    jobs:
#      - build
#      - deploy


version: 2.1

commands:
  print:
    parameters:
      message:
        type: string
    steps:
      - run: echo << parameters.message >>

jobs:
  cat-file:
    docker:
      - image: circleci/node:7.10
    parameters:
      file:
        type: string
    run: cat << parameters.file >>
    steps:
      - print:
          message: Printing << parameters.file >>
      - run: cat << parameters.file >>

workflows:
  my-workflow:
    jobs:
      - cat-file:
          file: test.txt